# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 565)
        MainWindow.setStyleSheet("background-color: rgb(17,17,17);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        self.insert_payment_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_payment_btn.sizePolicy().hasHeightForWidth())
        self.insert_payment_btn.setSizePolicy(sizePolicy)
        self.insert_payment_btn.setMinimumSize(QtCore.QSize(120, 40))
        self.insert_payment_btn.setMaximumSize(QtCore.QSize(0, 16777215))
        self.insert_payment_btn.setSizeIncrement(QtCore.QSize(0, 0))
        self.insert_payment_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.insert_payment_btn.setStyleSheet("QPushButton {\n"
"    font: 63 12pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"\n"
"}\n"
"QPushButton::hover {\n"
"    color: rgb(17, 17, 17);\n"
"    background-color: rgb(150,206,180);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: rgb(17, 17, 17);\n"
"    background-color: rgb(150,206,180);\n"
"    border: 2px solid white;\n"
"}")
        self.insert_payment_btn.setAutoDefault(False)
        self.insert_payment_btn.setDefault(False)
        self.insert_payment_btn.setFlat(False)
        self.insert_payment_btn.setObjectName("insert_payment_btn")
        self.horizontalLayout.addWidget(self.insert_payment_btn)
        self.amount_txt = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_txt.sizePolicy().hasHeightForWidth())
        self.amount_txt.setSizePolicy(sizePolicy)
        self.amount_txt.setMinimumSize(QtCore.QSize(100, 20))
        self.amount_txt.setMaximumSize(QtCore.QSize(600, 16777215))
        self.amount_txt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.amount_txt.setStyleSheet("QTextEdit {\n"
"    font: 63 16pt \"Segoe UI Semibold\";\n"
"    background-color: rgb(213, 213, 213);\n"
"    border-radius: 20px;\n"
"    text-align: right;\n"
"}\n"
"\n"
"QTextEdit::hover {\n"
"    background-color: rgb(150,206,180);\n"
"    text-align: right;\n"
"}\n"
"\n"
"QTextEdit::focus {\n"
"    background-color: rgb(150,206,180);\n"
"    border: 2px solid white;\n"
"    text-align: right;\n"
"}")
        self.amount_txt.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.amount_txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.amount_txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.amount_txt.setObjectName("amount_txt")
        self.horizontalLayout.addWidget(self.amount_txt)
        self.new_bill_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_bill_btn.sizePolicy().hasHeightForWidth())
        self.new_bill_btn.setSizePolicy(sizePolicy)
        self.new_bill_btn.setMinimumSize(QtCore.QSize(200, 50))
        self.new_bill_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_bill_btn.setToolTipDuration(-1)
        self.new_bill_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.new_bill_btn.setAutoFillBackground(False)
        self.new_bill_btn.setStyleSheet("QPushButton {\n"
"    font: 63 16pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    color: rgb(17, 17, 17);\n"
"    background-color: rgb(178,216,216);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: rgb(120,216,216);\n"
"}")
        self.new_bill_btn.setAutoDefault(False)
        self.new_bill_btn.setDefault(False)
        self.new_bill_btn.setFlat(False)
        self.new_bill_btn.setObjectName("new_bill_btn")
        self.horizontalLayout.addWidget(self.new_bill_btn)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(85, 85, 85);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.reset_btn = QtWidgets.QPushButton(self.frame_2)
        self.reset_btn.setGeometry(QtCore.QRect(1010, 410, 200, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_btn.sizePolicy().hasHeightForWidth())
        self.reset_btn.setSizePolicy(sizePolicy)
        self.reset_btn.setMinimumSize(QtCore.QSize(200, 40))
        self.reset_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_btn.setStyleSheet("QPushButton {\n"
"    font: 63 12pt \"Segoe UI Semibold\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    color: rgb(17, 17, 17);\n"
"    background-color: rgb(213, 213, 213);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: rgb(17, 17, 17);\n"
"    background-color: rgb(150,206,180);\n"
"    border: 2px solid white;\n"
"}")
        self.reset_btn.setAutoDefault(False)
        self.reset_btn.setDefault(False)
        self.reset_btn.setFlat(False)
        self.reset_btn.setObjectName("reset_btn")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(120, 50, 1011, 351))
        self.tableWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.insert_payment_btn.setToolTip(_translate("MainWindow", "הכנס פרטי תשלום חדש"))
        self.insert_payment_btn.setWhatsThis(_translate("MainWindow", "הכנס פרטי תשלום חדש"))
        self.insert_payment_btn.setText(_translate("MainWindow", "חיפוש"))
        self.amount_txt.setToolTip(_translate("MainWindow", "הכנס סכום לתשלום"))
        self.amount_txt.setWhatsThis(_translate("MainWindow", "הכנס סכום לתשלום"))
        self.amount_txt.setPlaceholderText(_translate("MainWindow", "                                                       ?מה תרצה לחפש"))
        self.new_bill_btn.setToolTip(_translate("MainWindow", "הוספת חשבון חדש"))
        self.new_bill_btn.setWhatsThis(_translate("MainWindow", "הוספת חשבון חדש"))
        self.new_bill_btn.setText(_translate("MainWindow", "חשבון חדש +"))
        self.reset_btn.setToolTip(_translate("MainWindow", "לחץ להפעלה מחדש"))
        self.reset_btn.setWhatsThis(_translate("MainWindow", "לחץ להפעלה מחדש"))
        self.reset_btn.setText(_translate("MainWindow", "הפעלה מחדש"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "מאכל"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "כמות"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "קלוריות"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "חלבון"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "קלוריות"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "פחמימות"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "כולסטרול"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "סיבים תזונתיים"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
